### ISSUE TITLE
Where on the physical camera is o3d3xx/camera_link located?

### ISSUE THREAD

**Issue by eirik-strand** [ifm/o3d3xx-ros#43]
In order to get correct distance readings I need to know where on the physical camera you are referencing points from

**Comment by tpanzarella** [comment]
The camera_link has its origin at the center of the camera glass. It uses a standard right-handed coord frame.

**Comment by eirik-strand** [comment]
Thank you for the quick response. I tried to use this frame as my reference, but I think my angle is a little wrong. Does the glass lens define a axis plane? Or is that one of the flat camera sides?
