### ISSUE TITLE
PointCloud<pcl::PointWithRange> range data

### ISSUE THREAD

**Issue by derektan95** [ifm/o3d3xx-ros#44]
Hi, 

I am having some trouble understand the point cloud data I am getting from my camera. I subscribed to the point cloud data from the camera, by defining the callback function in this manner:

void cloud_cb (const pcl::PointCloud<pcl::PointWithRange>::ConstPtr& input_const_ptr) {...}

I did this to obtain the range values associated to each point relative to the origin. However, I have been getting huge "range" values that does not seem to be in the standard units like meters or mm(as seen below). Is there a certain conversion factor for me to attain the actual range from the camera to each individual point? Thanks!

# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS x y z range
SIZE 4 4 4 4
TYPE F F F F
COUNT 1 1 1 1
WIDTH 176
HEIGHT 132
VIEWPOINT 0 0 0 1 0 0 0
POINTS 23232
DATA ascii
1.929 1.251 0.90799999 233
1.97 1.258 0.92400002 247
2.0020001 1.2589999 0.935 250
2.003 1.24 0.93099999 248
2.0090001 1.225 0.93000001 239
2.016 1.21 0.93000001 232
2.0179999 1.193 0.92799997 199
2.0309999 1.182 0.93000001 148
2.04 1.169 0.93099999 162
2.053 1.158 0.93400002 157
2.0569999 1.142 0.93199998 173
2.0639999 1.127 0.93199998 188

**Comment by derektan95** [comment]
Just some additional information. I got information about the point type from this website: http://pointclouds.org/documentation/tutorials/adding_custom_ptype.php

Just a side question: Is the position of the camera located at (0,0,0) relative to the point cloud?

**Comment by tpanzarella** [comment]
The point type we encode in the Point Cloud is `pcl:PointXYZI`, see [here](https://github.com/ifm/libo3d3xx/blob/master/modules/image/include/o3d3xx_image/image.h#L32). In this case we use the Amplitude value registered to the point as the "I" (intensity). 

Also, I would suggest using [ifm3d](https://github.com/ifm/ifm3d) and [ifm3d-ros](https://github.com/ifm/ifm3d-ros) in preference to much older [libo3d3xx](https://github.com/ifm/libo3d3xx) and [o3d3xx-ros](https://github.com/ifm/o3d3xx-ros) stack that you are using.

The optical center of the camera glass is located at 0,0,0 and all points are returned in the camera frame with x-forward, y-left, and z-up.

**Comment by derektan95** [comment]
Thank you so much for your detailed explanation! I made sure to recompute the range values for each point relative to origin for my own usage.
