### ISSUE TITLE
IFM 03X101

### ISSUE THREAD

**Issue by YashRunwal** [ifm/o3d3xx-ros#45]
Hello, Happy New Year! I have a IFM 03X101 Camera (3D-Camera). Can someone tell me if this package will work with my version of Camera? In the description of the package it is written that it works with 03D3XX camera versions. Therefore, I am unsure as to usability of the package with the version of the camera I have.

**Comment by graugans** [comment]
Hey @YashRunwal happy new year!

please use the [ifm3d-ros](https://github.com/ifm/ifm3d-ros) driver which comes with O3X support. The ``o3d3xx-ros`` package is based on the older [libo3d3xx](https://github.com/ifm/libo3d3xx) what does not provide support for the O3X family.
